# Create
POST {{HOST}}/user/create
Content-Type: application/json

{
  "name": "Ivan",
  "email": "ivan@email.ru"
}

###

# Get
POST {{HOST}}/user/get
Content-Type: application/json

{
  "id": 2
}

###

# List
POST {{HOST}}/user/list
Content-Type: application/json

{}

###

# Update
POST {{HOST}}/user/update
Content-Type: application/json

{
  "id": 3,
  "name": "Petr",
  "email": "petr@email.ru"
}

###

# Delete
POST {{HOST}}/user/delete
Content-Type: application/json

{
  "id": 3
}

###